
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestMaster.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 DO = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
INTEGER16 AO1 = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
INTEGER16 AO2 = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
INTEGER16 AO3 = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
INTEGER16 AO4 = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
INTEGER16 AI1 = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
INTEGER16 AI2 = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
INTEGER16 AI3 = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
INTEGER16 AI4 = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
INTEGER16 AI5 = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
INTEGER16 AI6 = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
INTEGER16 AI7 = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
INTEGER16 AI8 = 0x0;		/* Mapped at index 0x200C, subindex 0x00 */
UNS8 DI1 = 0x0;		/* Mapped at index 0x200F, subindex 0x00 */
UNS8 DI2 = 0x0;		/* Mapped at index 0x2010, subindex 0x00 */
UNS8 DI3 = 0x0;		/* Mapped at index 0x2011, subindex 0x00 */
UNS8 DI4 = 0x0;		/* Mapped at index 0x2012, subindex 0x00 */
UNS8 DI5 = 0x0;		/* Mapped at index 0x2013, subindex 0x00 */
UNS8 DI6 = 0x0;		/* Mapped at index 0x2014, subindex 0x00 */
UNS8 DI7 = 0x0;		/* Mapped at index 0x2015, subindex 0x00 */
UNS8 DI8 = 0x0;		/* Mapped at index 0x2016, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestMaster_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestMaster_iam_a_slave = 0;

TIMER_HANDLE TestMaster_heartBeatTimers[9] = {TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestMaster_obj1000 = 0x191;	/* 401 */
                    subindex TestMaster_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestMaster_obj1001 = 0x0;	/* 0 */
                    subindex TestMaster_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestMaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex TestMaster_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 TestMaster_obj1005 = 0x40000080;	/* 1073741952 */
                    subindex TestMaster_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 TestMaster_obj1006 = 0xC350;	/* 50000 */
                    subindex TestMaster_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1006, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 TestMaster_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestMaster_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 TestMaster_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 TestMaster_highestSubIndex_obj1016 = 9; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1016[] = 
                    {
                      0x32710,	/* 206608 */
                      0x42710,	/* 272144 */
                      0x52710,	/* 337680 */
                      0x62710,	/* 403216 */
                      0x72710,	/* 468752 */
                      0x82710,	/* 534288 */
                      0x22710,	/* 141072 */
                      0x12710,	/* 75536 */
                      0x92710	/* 599824 */
                    };
                    subindex TestMaster_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1016, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[7], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1016[8], NULL }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 TestMaster_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 TestMaster_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestMaster_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex TestMaster_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TestMaster_obj1018_Serial_Number, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x641;	/* 1601 */
                    UNS32 TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x5C1;	/* 1473 */
                    UNS8 TestMaster_obj1280_Node_ID_of_the_SDO_Server = 0x41;	/* 65 */
                    subindex TestMaster_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x633;	/* 1587 */
                    UNS32 TestMaster_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x5B3;	/* 1459 */
                    UNS8 TestMaster_obj1281_Node_ID_of_the_SDO_Server = 0x33;	/* 51 */
                    subindex TestMaster_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1281, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1281_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1281_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1281_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x666;	/* 1638 */
                    UNS32 TestMaster_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x5E6;	/* 1510 */
                    UNS8 TestMaster_obj1282_Node_ID_of_the_SDO_Server = 0x66;	/* 102 */
                    subindex TestMaster_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1282, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1282_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1282_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1282_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x622;	/* 1570 */
                    UNS32 TestMaster_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x5A2;	/* 1442 */
                    UNS8 TestMaster_obj1283_Node_ID_of_the_SDO_Server = 0x22;	/* 34 */
                    subindex TestMaster_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1283, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1283_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1283_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1283_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x623;	/* 1571 */
                    UNS32 TestMaster_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x5A3;	/* 1443 */
                    UNS8 TestMaster_obj1284_Node_ID_of_the_SDO_Server = 0x23;	/* 35 */
                    subindex TestMaster_Index1284[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1284, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1284_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1284_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1284_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1285 :   Client SDO 6 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1285 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1285_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 TestMaster_obj1285_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 TestMaster_obj1285_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex TestMaster_Index1285[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1285, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1285_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1285_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1285_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1286 :   Client SDO 7 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1286 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1286_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 TestMaster_obj1286_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 TestMaster_obj1286_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex TestMaster_Index1286[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1286, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1286_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1286_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1286_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1287 :   Client SDO 8 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1287 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1287_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 TestMaster_obj1287_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 TestMaster_obj1287_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex TestMaster_Index1287[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1287, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1287_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1287_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1287_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1288 :   Client SDO 9 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1288 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1288_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1540 */
                    UNS32 TestMaster_obj1288_COB_ID_Server_to_Client_Receive_SDO = 0x584;	/* 1412 */
                    UNS8 TestMaster_obj1288_Node_ID_of_the_SDO_Server = 0x4;	/* 4 */
                    subindex TestMaster_Index1288[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1288, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1288_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1288_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1288_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1289 :   Client SDO 10 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1289 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1289_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/* 1541 */
                    UNS32 TestMaster_obj1289_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/* 1413 */
                    UNS8 TestMaster_obj1289_Node_ID_of_the_SDO_Server = 0x5;	/* 5 */
                    subindex TestMaster_Index1289[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1289, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1289_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1289_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1289_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128A :   Client SDO 11 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj128A = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj128A_COB_ID_Client_to_Server_Transmit_SDO = 0x606;	/* 1542 */
                    UNS32 TestMaster_obj128A_COB_ID_Server_to_Client_Receive_SDO = 0x586;	/* 1414 */
                    UNS8 TestMaster_obj128A_Node_ID_of_the_SDO_Server = 0x6;	/* 6 */
                    subindex TestMaster_Index128A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj128A, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128A_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128A_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj128A_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128B :   Client SDO 12 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj128B = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj128B_COB_ID_Client_to_Server_Transmit_SDO = 0x607;	/* 1543 */
                    UNS32 TestMaster_obj128B_COB_ID_Server_to_Client_Receive_SDO = 0x587;	/* 1415 */
                    UNS8 TestMaster_obj128B_Node_ID_of_the_SDO_Server = 0x7;	/* 7 */
                    subindex TestMaster_Index128B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj128B, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128B_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128B_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj128B_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128C :   Client SDO 13 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj128C = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj128C_COB_ID_Client_to_Server_Transmit_SDO = 0x608;	/* 1544 */
                    UNS32 TestMaster_obj128C_COB_ID_Server_to_Client_Receive_SDO = 0x588;	/* 1416 */
                    UNS8 TestMaster_obj128C_Node_ID_of_the_SDO_Server = 0x8;	/* 8 */
                    subindex TestMaster_Index128C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj128C, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128C_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128C_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj128C_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128D :   Client SDO 14 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj128D = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj128D_COB_ID_Client_to_Server_Transmit_SDO = 0x609;	/* 1545 */
                    UNS32 TestMaster_obj128D_COB_ID_Server_to_Client_Receive_SDO = 0x589;	/* 1417 */
                    UNS8 TestMaster_obj128D_Node_ID_of_the_SDO_Server = 0x9;	/* 9 */
                    subindex TestMaster_Index128D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj128D, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128D_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128D_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj128D_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128E :   Client SDO 15 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj128E = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj128E_COB_ID_Client_to_Server_Transmit_SDO = 0x60A;	/* 1546 */
                    UNS32 TestMaster_obj128E_COB_ID_Server_to_Client_Receive_SDO = 0x58A;	/* 1418 */
                    UNS8 TestMaster_obj128E_Node_ID_of_the_SDO_Server = 0xA;	/* 10 */
                    subindex TestMaster_Index128E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj128E, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128E_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128E_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj128E_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128F :   Client SDO 16 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj128F = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj128F_COB_ID_Client_to_Server_Transmit_SDO = 0x60B;	/* 1547 */
                    UNS32 TestMaster_obj128F_COB_ID_Server_to_Client_Receive_SDO = 0x58B;	/* 1419 */
                    UNS8 TestMaster_obj128F_Node_ID_of_the_SDO_Server = 0xB;	/* 11 */
                    subindex TestMaster_Index128F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj128F, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128F_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj128F_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj128F_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1290 :   Client SDO 17 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1290 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1290_COB_ID_Client_to_Server_Transmit_SDO = 0x60C;	/* 1548 */
                    UNS32 TestMaster_obj1290_COB_ID_Server_to_Client_Receive_SDO = 0x58C;	/* 1420 */
                    UNS8 TestMaster_obj1290_Node_ID_of_the_SDO_Server = 0xC;	/* 12 */
                    subindex TestMaster_Index1290[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1290, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1290_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1290_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1290_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1291 :   Client SDO 18 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1291 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1291_COB_ID_Client_to_Server_Transmit_SDO = 0x60D;	/* 1549 */
                    UNS32 TestMaster_obj1291_COB_ID_Server_to_Client_Receive_SDO = 0x58D;	/* 1421 */
                    UNS8 TestMaster_obj1291_Node_ID_of_the_SDO_Server = 0xD;	/* 13 */
                    subindex TestMaster_Index1291[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1291, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1291_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1291_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1291_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1292 :   Client SDO 19 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1292 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1292_COB_ID_Client_to_Server_Transmit_SDO = 0x60E;	/* 1550 */
                    UNS32 TestMaster_obj1292_COB_ID_Server_to_Client_Receive_SDO = 0x58E;	/* 1422 */
                    UNS8 TestMaster_obj1292_Node_ID_of_the_SDO_Server = 0xE;	/* 14 */
                    subindex TestMaster_Index1292[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1292, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1292_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1292_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1292_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1293 :   Client SDO 20 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1293 = 3; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1293_COB_ID_Client_to_Server_Transmit_SDO = 0x60F;	/* 1551 */
                    UNS32 TestMaster_obj1293_COB_ID_Server_to_Client_Receive_SDO = 0x58F;	/* 1423 */
                    UNS8 TestMaster_obj1293_Node_ID_of_the_SDO_Server = 0xF;	/* 15 */
                    subindex TestMaster_Index1293[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1293, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1293_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1293_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1293_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1400_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 TestMaster_obj1400_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex TestMaster_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1400_Event_Timer, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1401 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1401_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 TestMaster_obj1401_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1401_Event_Timer = 0x0;	/* 0 */
                    subindex TestMaster_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1401_Event_Timer, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1402 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1402_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 TestMaster_obj1402_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TestMaster_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1402_Event_Timer = 0x0;	/* 0 */
                    subindex TestMaster_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1402_Event_Timer, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1600[] = 
                    {
                      0x200F0001,	/* 537853953 */
                      0x20100001,	/* 537919489 */
                      0x20110001,	/* 537985025 */
                      0x20120001,	/* 538050561 */
                      0x20130001,	/* 538116097 */
                      0x20140001,	/* 538181633 */
                      0x20150001,	/* 538247169 */
                      0x20160001	/* 538312705 */
                    };
                    subindex TestMaster_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1600[7], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1601 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1601[] = 
                    {
                      0x20050010,	/* 537198608 */
                      0x20060010,	/* 537264144 */
                      0x20070010,	/* 537329680 */
                      0x20080010	/* 537395216 */
                    };
                    subindex TestMaster_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1601[3], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1602 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1602[] = 
                    {
                      0x20090010,	/* 537460752 */
                      0x200A0010,	/* 537526288 */
                      0x200B0010,	/* 537591824 */
                      0x200C0010	/* 537657360 */
                    };
                    subindex TestMaster_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1602[3], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1800_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 TestMaster_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1800_Event_Timer = 0x0;	/* 0 */
                    subindex TestMaster_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1800_Event_Timer, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 TestMaster_highestSubIndex_obj1801 = 5; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1801_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 TestMaster_obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestMaster_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestMaster_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestMaster_obj1801_Event_Timer = 0x0;	/* 0 */
                    subindex TestMaster_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TestMaster_obj1801_Event_Timer, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A00[] = 
                    {
                      0x20000008	/* 536870920 */
                    };
                    subindex TestMaster_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A00[0], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 TestMaster_highestSubIndex_obj1A01 = 4; /* number of subindex - 1*/
                    UNS32 TestMaster_obj1A01[] = 
                    {
                      0x20010010,	/* 536936464 */
                      0x20020010,	/* 537002000 */
                      0x20030010,	/* 537067536 */
                      0x20040010	/* 537133072 */
                    };
                    subindex TestMaster_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestMaster_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TestMaster_obj1A01[3], NULL }
                     };

/* index 0x2000 :   Mapped variable DO */
                    subindex TestMaster_Index2000[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&DO, NULL }
                     };

/* index 0x2001 :   Mapped variable AO1 */
                    subindex TestMaster_Index2001[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AO1, NULL }
                     };

/* index 0x2002 :   Mapped variable AO2 */
                    subindex TestMaster_Index2002[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AO2, NULL }
                     };

/* index 0x2003 :   Mapped variable AO3 */
                    subindex TestMaster_Index2003[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AO3, NULL }
                     };

/* index 0x2004 :   Mapped variable AO4 */
                    subindex TestMaster_Index2004[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AO4, NULL }
                     };

/* index 0x2005 :   Mapped variable AI1 */
                    subindex TestMaster_Index2005[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI1, NULL }
                     };

/* index 0x2006 :   Mapped variable AI2 */
                    subindex TestMaster_Index2006[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI2, NULL }
                     };

/* index 0x2007 :   Mapped variable AI3 */
                    subindex TestMaster_Index2007[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI3, NULL }
                     };

/* index 0x2008 :   Mapped variable AI4 */
                    subindex TestMaster_Index2008[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI4, NULL }
                     };

/* index 0x2009 :   Mapped variable AI5 */
                    subindex TestMaster_Index2009[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI5, NULL }
                     };

/* index 0x200A :   Mapped variable AI6 */
                    subindex TestMaster_Index200A[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI6, NULL }
                     };

/* index 0x200B :   Mapped variable AI7 */
                    subindex TestMaster_Index200B[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI7, NULL }
                     };

/* index 0x200C :   Mapped variable AI8 */
                    subindex TestMaster_Index200C[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&AI8, NULL }
                     };

/* index 0x200F :   Mapped variable DI1 */
                    subindex TestMaster_Index200F[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI1, NULL }
                     };

/* index 0x2010 :   Mapped variable DI2 */
                    subindex TestMaster_Index2010[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI2, NULL }
                     };

/* index 0x2011 :   Mapped variable DI3 */
                    subindex TestMaster_Index2011[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI3, NULL }
                     };

/* index 0x2012 :   Mapped variable DI4 */
                    subindex TestMaster_Index2012[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI4, NULL }
                     };

/* index 0x2013 :   Mapped variable DI5 */
                    subindex TestMaster_Index2013[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI5, NULL }
                     };

/* index 0x2014 :   Mapped variable DI6 */
                    subindex TestMaster_Index2014[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI6, NULL }
                     };

/* index 0x2015 :   Mapped variable DI7 */
                    subindex TestMaster_Index2015[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI7, NULL }
                     };

/* index 0x2016 :   Mapped variable DI8 */
                    subindex TestMaster_Index2016[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&DI8, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestMaster_objdict[] = 
{
  { (subindex*)TestMaster_Index1000,sizeof(TestMaster_Index1000)/sizeof(TestMaster_Index1000[0]), 0x1000},
  { (subindex*)TestMaster_Index1001,sizeof(TestMaster_Index1001)/sizeof(TestMaster_Index1001[0]), 0x1001},
  { (subindex*)TestMaster_Index1005,sizeof(TestMaster_Index1005)/sizeof(TestMaster_Index1005[0]), 0x1005},
  { (subindex*)TestMaster_Index1006,sizeof(TestMaster_Index1006)/sizeof(TestMaster_Index1006[0]), 0x1006},
  { (subindex*)TestMaster_Index1016,sizeof(TestMaster_Index1016)/sizeof(TestMaster_Index1016[0]), 0x1016},
  { (subindex*)TestMaster_Index1018,sizeof(TestMaster_Index1018)/sizeof(TestMaster_Index1018[0]), 0x1018},
  { (subindex*)TestMaster_Index1280,sizeof(TestMaster_Index1280)/sizeof(TestMaster_Index1280[0]), 0x1280},
  { (subindex*)TestMaster_Index1281,sizeof(TestMaster_Index1281)/sizeof(TestMaster_Index1281[0]), 0x1281},
  { (subindex*)TestMaster_Index1282,sizeof(TestMaster_Index1282)/sizeof(TestMaster_Index1282[0]), 0x1282},
  { (subindex*)TestMaster_Index1283,sizeof(TestMaster_Index1283)/sizeof(TestMaster_Index1283[0]), 0x1283},
  { (subindex*)TestMaster_Index1284,sizeof(TestMaster_Index1284)/sizeof(TestMaster_Index1284[0]), 0x1284},
  { (subindex*)TestMaster_Index1285,sizeof(TestMaster_Index1285)/sizeof(TestMaster_Index1285[0]), 0x1285},
  { (subindex*)TestMaster_Index1286,sizeof(TestMaster_Index1286)/sizeof(TestMaster_Index1286[0]), 0x1286},
  { (subindex*)TestMaster_Index1287,sizeof(TestMaster_Index1287)/sizeof(TestMaster_Index1287[0]), 0x1287},
  { (subindex*)TestMaster_Index1288,sizeof(TestMaster_Index1288)/sizeof(TestMaster_Index1288[0]), 0x1288},
  { (subindex*)TestMaster_Index1289,sizeof(TestMaster_Index1289)/sizeof(TestMaster_Index1289[0]), 0x1289},
  { (subindex*)TestMaster_Index128A,sizeof(TestMaster_Index128A)/sizeof(TestMaster_Index128A[0]), 0x128A},
  { (subindex*)TestMaster_Index128B,sizeof(TestMaster_Index128B)/sizeof(TestMaster_Index128B[0]), 0x128B},
  { (subindex*)TestMaster_Index128C,sizeof(TestMaster_Index128C)/sizeof(TestMaster_Index128C[0]), 0x128C},
  { (subindex*)TestMaster_Index128D,sizeof(TestMaster_Index128D)/sizeof(TestMaster_Index128D[0]), 0x128D},
  { (subindex*)TestMaster_Index128E,sizeof(TestMaster_Index128E)/sizeof(TestMaster_Index128E[0]), 0x128E},
  { (subindex*)TestMaster_Index128F,sizeof(TestMaster_Index128F)/sizeof(TestMaster_Index128F[0]), 0x128F},
  { (subindex*)TestMaster_Index1290,sizeof(TestMaster_Index1290)/sizeof(TestMaster_Index1290[0]), 0x1290},
  { (subindex*)TestMaster_Index1291,sizeof(TestMaster_Index1291)/sizeof(TestMaster_Index1291[0]), 0x1291},
  { (subindex*)TestMaster_Index1292,sizeof(TestMaster_Index1292)/sizeof(TestMaster_Index1292[0]), 0x1292},
  { (subindex*)TestMaster_Index1293,sizeof(TestMaster_Index1293)/sizeof(TestMaster_Index1293[0]), 0x1293},
  { (subindex*)TestMaster_Index1400,sizeof(TestMaster_Index1400)/sizeof(TestMaster_Index1400[0]), 0x1400},
  { (subindex*)TestMaster_Index1401,sizeof(TestMaster_Index1401)/sizeof(TestMaster_Index1401[0]), 0x1401},
  { (subindex*)TestMaster_Index1402,sizeof(TestMaster_Index1402)/sizeof(TestMaster_Index1402[0]), 0x1402},
  { (subindex*)TestMaster_Index1600,sizeof(TestMaster_Index1600)/sizeof(TestMaster_Index1600[0]), 0x1600},
  { (subindex*)TestMaster_Index1601,sizeof(TestMaster_Index1601)/sizeof(TestMaster_Index1601[0]), 0x1601},
  { (subindex*)TestMaster_Index1602,sizeof(TestMaster_Index1602)/sizeof(TestMaster_Index1602[0]), 0x1602},
  { (subindex*)TestMaster_Index1800,sizeof(TestMaster_Index1800)/sizeof(TestMaster_Index1800[0]), 0x1800},
  { (subindex*)TestMaster_Index1801,sizeof(TestMaster_Index1801)/sizeof(TestMaster_Index1801[0]), 0x1801},
  { (subindex*)TestMaster_Index1A00,sizeof(TestMaster_Index1A00)/sizeof(TestMaster_Index1A00[0]), 0x1A00},
  { (subindex*)TestMaster_Index1A01,sizeof(TestMaster_Index1A01)/sizeof(TestMaster_Index1A01[0]), 0x1A01},
  { (subindex*)TestMaster_Index2000,sizeof(TestMaster_Index2000)/sizeof(TestMaster_Index2000[0]), 0x2000},
  { (subindex*)TestMaster_Index2001,sizeof(TestMaster_Index2001)/sizeof(TestMaster_Index2001[0]), 0x2001},
  { (subindex*)TestMaster_Index2002,sizeof(TestMaster_Index2002)/sizeof(TestMaster_Index2002[0]), 0x2002},
  { (subindex*)TestMaster_Index2003,sizeof(TestMaster_Index2003)/sizeof(TestMaster_Index2003[0]), 0x2003},
  { (subindex*)TestMaster_Index2004,sizeof(TestMaster_Index2004)/sizeof(TestMaster_Index2004[0]), 0x2004},
  { (subindex*)TestMaster_Index2005,sizeof(TestMaster_Index2005)/sizeof(TestMaster_Index2005[0]), 0x2005},
  { (subindex*)TestMaster_Index2006,sizeof(TestMaster_Index2006)/sizeof(TestMaster_Index2006[0]), 0x2006},
  { (subindex*)TestMaster_Index2007,sizeof(TestMaster_Index2007)/sizeof(TestMaster_Index2007[0]), 0x2007},
  { (subindex*)TestMaster_Index2008,sizeof(TestMaster_Index2008)/sizeof(TestMaster_Index2008[0]), 0x2008},
  { (subindex*)TestMaster_Index2009,sizeof(TestMaster_Index2009)/sizeof(TestMaster_Index2009[0]), 0x2009},
  { (subindex*)TestMaster_Index200A,sizeof(TestMaster_Index200A)/sizeof(TestMaster_Index200A[0]), 0x200A},
  { (subindex*)TestMaster_Index200B,sizeof(TestMaster_Index200B)/sizeof(TestMaster_Index200B[0]), 0x200B},
  { (subindex*)TestMaster_Index200C,sizeof(TestMaster_Index200C)/sizeof(TestMaster_Index200C[0]), 0x200C},
  { (subindex*)TestMaster_Index200F,sizeof(TestMaster_Index200F)/sizeof(TestMaster_Index200F[0]), 0x200F},
  { (subindex*)TestMaster_Index2010,sizeof(TestMaster_Index2010)/sizeof(TestMaster_Index2010[0]), 0x2010},
  { (subindex*)TestMaster_Index2011,sizeof(TestMaster_Index2011)/sizeof(TestMaster_Index2011[0]), 0x2011},
  { (subindex*)TestMaster_Index2012,sizeof(TestMaster_Index2012)/sizeof(TestMaster_Index2012[0]), 0x2012},
  { (subindex*)TestMaster_Index2013,sizeof(TestMaster_Index2013)/sizeof(TestMaster_Index2013[0]), 0x2013},
  { (subindex*)TestMaster_Index2014,sizeof(TestMaster_Index2014)/sizeof(TestMaster_Index2014[0]), 0x2014},
  { (subindex*)TestMaster_Index2015,sizeof(TestMaster_Index2015)/sizeof(TestMaster_Index2015[0]), 0x2015},
  { (subindex*)TestMaster_Index2016,sizeof(TestMaster_Index2016)/sizeof(TestMaster_Index2016[0]), 0x2016},
};

const indextable * TestMaster_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1016: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1280: i = 6;break;
		case 0x1281: i = 7;break;
		case 0x1282: i = 8;break;
		case 0x1283: i = 9;break;
		case 0x1284: i = 10;break;
		case 0x1285: i = 11;break;
		case 0x1286: i = 12;break;
		case 0x1287: i = 13;break;
		case 0x1288: i = 14;break;
		case 0x1289: i = 15;break;
		case 0x128A: i = 16;break;
		case 0x128B: i = 17;break;
		case 0x128C: i = 18;break;
		case 0x128D: i = 19;break;
		case 0x128E: i = 20;break;
		case 0x128F: i = 21;break;
		case 0x1290: i = 22;break;
		case 0x1291: i = 23;break;
		case 0x1292: i = 24;break;
		case 0x1293: i = 25;break;
		case 0x1400: i = 26;break;
		case 0x1401: i = 27;break;
		case 0x1402: i = 28;break;
		case 0x1600: i = 29;break;
		case 0x1601: i = 30;break;
		case 0x1602: i = 31;break;
		case 0x1800: i = 32;break;
		case 0x1801: i = 33;break;
		case 0x1A00: i = 34;break;
		case 0x1A01: i = 35;break;
		case 0x2000: i = 36;break;
		case 0x2001: i = 37;break;
		case 0x2002: i = 38;break;
		case 0x2003: i = 39;break;
		case 0x2004: i = 40;break;
		case 0x2005: i = 41;break;
		case 0x2006: i = 42;break;
		case 0x2007: i = 43;break;
		case 0x2008: i = 44;break;
		case 0x2009: i = 45;break;
		case 0x200A: i = 46;break;
		case 0x200B: i = 47;break;
		case 0x200C: i = 48;break;
		case 0x200F: i = 49;break;
		case 0x2010: i = 50;break;
		case 0x2011: i = 51;break;
		case 0x2012: i = 52;break;
		case 0x2013: i = 53;break;
		case 0x2014: i = 54;break;
		case 0x2015: i = 55;break;
		case 0x2016: i = 56;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestMaster_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestMaster_PDO_status[2] = {s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index TestMaster_firstIndex = {
  0, /* SDO_SVR */
  6, /* SDO_CLT */
  26, /* PDO_RCV */
  29, /* PDO_RCV_MAP */
  32, /* PDO_TRS */
  34 /* PDO_TRS_MAP */
};

const quick_index TestMaster_lastIndex = {
  0, /* SDO_SVR */
  25, /* SDO_CLT */
  28, /* PDO_RCV */
  31, /* PDO_RCV_MAP */
  33, /* PDO_TRS */
  35 /* PDO_TRS_MAP */
};

const UNS16 TestMaster_ObjdictSize = sizeof(TestMaster_objdict)/sizeof(TestMaster_objdict[0]); 

CO_Data TestMaster_Data = CANOPEN_NODE_DATA_INITIALIZER(TestMaster);

